language: rust

rust:
  - nightly
  - beta
  - stable

sudo: false

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc

after_success: if [ "$TRAVIS_RUST_VERSION" = stable ]; then curl https://raw.githubusercontent.com/kmcallister/travis-doc-upload/master/travis-doc-upload.sh | sh; fi

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
