language: rust

rust:
  - nightly
  - beta
  - stable

sudo: false

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo bench
  - cargo doc

after_success: curl https://raw.githubusercontent.com/kmcallister/travis-doc-upload/master/travis-doc-upload.sh | sh

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
