language: rust
branches:
  except:
    - gh-pages
sudo: false
env:
  global:
    secure: KrSphUaXPC4Q4hcdnwViMzYmgJ7o5cNRMT7cpzGdjvrnMyEzYyQCd/rynWbajQLywanaEe6iafq4dtQVmK0LSMXXRw4qLpp9NNTn2l1o8qz2QhDMy2gDxzZyOCI0aZJadcFcvpH2OgQ5ui76AVXAHln8IaKWPVYjUjiHjaDQE2M=
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc --verbose
after_success: |
  [ $TRAVIS_PULL_REQUEST = false ] &&
  [ $TRAVIS_BRANCH = master ] &&
  [ $(uname -s) = Linux ] &&
  ./upload_docs
